spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1;databaseName=school
    username: sa
    password: 235610
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
server:
  port: 8081
  servlet:
    context-path: /api/